### ISSUE TITLE
plugin not work in Web

### ISSUE THREAD

**Issue by nadim-git** [tchvu3/capacitor-voice-recorder#21]
Error: MISSING_PERMISSION
    at missingPermissionError (predefined-web-responses.js?600f:3:1)
    at VoiceRecorderImpl.startRecording (VoiceRecorderImpl.js?7f8d:31:1)

**Comment by sultanmyrza** [comment]
<details>
<summary> [ionic + capacitor] this is my package.json (click to expand)</summary>

```json
{
 "dependencies": {
    "@angular/common": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/router": "^14.0.0",
    "@capacitor/app": "1.1.1",
    "@capacitor/core": "3.5.1",
    "@capacitor/filesystem": "^1.1.0",
    "@capacitor/haptics": "1.1.4",
    "@capacitor/keyboard": "1.2.2",
    "@capacitor/status-bar": "1.0.8",
    "@capacitor/storage": "^1.2.5",
    "@ionic/angular": "^6.1.9",
    "@ionic/pwa-elements": "^3.1.1",
    "capacitor-voice-recorder": "^2.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
}
```

</details>

calling `await VoiceRecorder.startRecording();` on localhost `web` throws this error

```
Error: MISSING_PERMISSION
    at missingPermissionError (predefined-web-responses.js:3:45)
    at VoiceRecorderImpl.js:31:41
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at _ZoneDelegate.invoke (zone.js:409:30)
    at Object.onInvoke (core.mjs:26515:33)
    at _ZoneDelegate.invoke (zone.js:408:56)
    at Zone.run (zone.js:169:47)
    at zone.js:1326:38
```
